name: CI

on: 
  push:
    branches:
      - master

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.0

    - name: Ruby cache
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Update bundler
      working-directory: ./Example
      run: bundle update --bundler
    - name: Bundle install
      working-directory: ./Example
      run: bundle install
    - name: Pod install
      working-directory: ./Example
      run: bundle exec pod install
    - name: Build and test
      working-directory: ./Example
      run: bundle exec fastlane tests
    - name: Pod lib lint
      run: pod lib lint CollectionModelCore.podspec
