name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update bundler
      working-directory: ./Example
      run: bundle update --bundler
    - name: Bundle install
      working-directory: ./Example
      run: bundle install
    - name: Pod install
      working-directory: ./Example
      run: bundle exec pod install
    - name: Build and test
      working-directory: ./Example
      run: bundle exec fastlane tests
    - name: Pod lib lint
      run: pod lib lint
